version: '3'
services:

  elasticsearch:
    image: elasticsearch:8.5.3
    environment:
      - xpack.security.enabled=false
      - "discovery.type=single-node"
    expose:
      - "9200"
    ports:
      - "9200:9200"

  kibana:
    image: kibana:8.5.3
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
